MeshJS/mesh

README.md
small corrections to English to correct grammar and make it clearer
=> Fix english grammar

packages/module/src/common/constants.ts
Lace is now live on mainnet (and supports CIP-30)! https://twitter.com/lace_io/status/1645755160935772161 
LGTM 🎉
=> Add support for Lace

packages/module/src/providers/maestro.provider.ts
=> Feat 129: Maestro Provider

packages/module/src/common/contracts/fetcher.ts, packages/module/src/common/types/TxUTxOs.ts, packages/module/src/common/types/index.ts, packages/module/src/common/utils/resolver.ts, packages/module/src/providers/blockfrost.provider.ts, packages/module/src/providers/koios.provider.ts, packages/module/src/providers/tango.provider.ts
Implementation of EricTsai decodeTransaction in Mesh ref# [here](https://gist.github.com/eric248550/c49af579c8405b3fed688fbf6d60fbac).
Added decode transaction function to resolver, added new TxUTxOs type, updated blockfrost, koios, and tango providers with fetchTransactionUTxOs functions.
Example usage and output.
```
const tx = new Transaction({ initiator: wallet })
.sendLovelace(
"addr_test1vpvx0sacufuypa2k4sngk7q40zc5c4npl337uusdh64kv0c7e4cxr",
"10000000"
)
.sendAssets(
"addr_test1vpvx0sacufuypa2k4sngk7q40zc5c4npl337uusdh64kv0c7e4cxr",
[
{
unit: "48664e8d76f2b15606677bd117a3eac9929c378ac547ed295518dfd574426967546f6b656e4e616d653032",
quantity: "1",
},
]
)
.sendAssets(
"addr_test1vpvx0sacufuypa2k4sngk7q40zc5c4npl337uusdh64kv0c7e4cxr",
[
{
unit: …
```
=> Decode Transaction.

packages/module/src/providers/koios.provider.ts
* Set the default Koios API version to "1" since [POST] https://preprod.koios.rest/api/v0/address_info returns a `404`.
* Previously, there was no error handling in place if no Koios API key had been provided; it would result in a `403` error due to a malformed API token, as the authentication header was set to `bearer undefined`. This issue caused fetchAddressUTxOs to simply `return []` without throwing an error (debugging took a while 😉). Therefore, a check has been added to the constructor of KoiosProvider, ensuring that the authentication header is not added if no header has been provided. Consequently, Koios now defaults (without providing an API token) to using the public tier instead of the free tier plan: https://koios.rest/pricing/Pricing.html. It may trigger a CORS error in a …
=> feat: support Koios public tier plan

packages/docs/src/data/api.json, packages/module/package.json, packages/module/src/core/CIP1852.ts, packages/module/src/wallet/app.service.ts, packages/module/src/wallet/browser.service.ts, packages/module/src/wallet/embedded.service.ts, yarn.lock
Since key derivation depends both on account index, and key index, I've changed the apis to expose both indexes for key derivation.
=> Feature update/cip1852 update

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json
due to preprod hardfork, cost models have been updated on sidan-csl-rs side.
=> bump sidan-csl-rs ver

CONTRIBUTING.md, README.md, packages/mesh-core/README.md
update readme to improve contributor onboarding
=> Contributor process and docs

packages/mesh-contract/src/royalties/cip102.md
> minor fix
> Please add the related issue here if any, e.g.:
>
> - Issue - [#329](https://github.com/MeshJS/mesh/issues/329)
=> docs: update cip102.md

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core-cst/src/message-signing/check-signature.ts, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
checkSignature in the core-cst library now accepts an optional 'address' parameter to validate against the address found in the signature.
Using the logic from this library: https://github.com/cardano-foundation/cardano-verify-datasignature, I basically just adjusted for the primitives used already in this library.
- https://github.com/MeshJS/mesh/issues/380#issue-2650883907
- https://github.com/MeshJS/mesh/issues/346#issue-2607741806
- https://github.com/MeshJS/mesh/issues/345#issue-2607718330
- #392
=> Fix bip32 public key

apps/playground/src/pages/apis/txbuilder/governance/deregistration.tsx, apps/playground/src/pages/apis/txbuilder/governance/index.tsx, apps/playground/src/pages/apis/txbuilder/governance/update.tsx, apps/playground/src/pages/home/index.tsx, apps/playground/src/pages/providers/blockfrost.tsx, package-lock.json, packages/mesh-transaction/src/mesh-tx-builder/tx-builder-core.ts
add update endpoint for gov tx
=> gov update

apps/playground/src/pages/react/ui-components/connect-wallet.tsx, apps/playground/src/pages/svelte/getting-started/index.tsx, apps/playground/src/pages/svelte/getting-started/state.tsx, apps/playground/src/pages/svelte/ui-components/connect-wallet.tsx, packages/mesh-svelte/src/lib/cardano-wallet/component/connect-wallet-button.svelte, packages/mesh-svelte/src/lib/cardano-wallet/component/index.ts, packages/mesh-svelte/src/lib/cardano-wallet/component/types.ts, packages/mesh-svelte/src/lib/cardano-wallet/state/browser-wallet-state.svelte.ts
- update state endpoints
- docs update
=> svelte 0.0.6

apps/playground/src/pages/react/ui-components/connect-wallet.tsx, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-react/src/cardano-wallet/connected-button.tsx, packages/mesh-react/src/cardano-wallet/index.tsx, packages/mesh-react/src/cardano-wallet/screen-main.tsx, packages/mesh-react/src/cardano-wallet/screen-p2p.tsx, packages/mesh-react/src/common/cardano-peer-connect/index.ts, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Fix CIP45 wallet connect UI issue
=> fix cip45 react UI component and bump version

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
add react peer dependencies
- #148
=> add peer depend and bump version

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/test/transaction/sendAssets.test.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
The serializer had hardcoded values for min utxo value calculations, it has been updated to use custom protocol parameters in the case that it is given.
=> fix min utxo calc

apps/playground/src/components/cardano/connect-browser-wallet.tsx, apps/playground/src/pages/react/ui-components/connect-wallet.tsx, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-react/src/cardano-wallet/connected-button.tsx, packages/mesh-react/src/cardano-wallet/index.tsx, packages/mesh-react/src/cardano-wallet/screen-p2p.tsx, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json, scripts/mesh-cli/src/actions/create.ts, scripts/mesh-cli/src/index.ts
- working cip45
- add svelte template to cli
=> Feat cip45

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Thank you for contributing to Mesh! We appreciate your effort and dedication to improving this project. To ensure that your contribution is in line with the project's guidelines and can be reviewed efficiently, please fill out the template below.
Remember to follow our [Contributing Guide](CONTRIBUTING.md) before submitting your pull request.
Bump version for customizable PP and cost model for hydra tx.
=> feat: bump ver

apps/playground/src/pages/svelte/getting-started/state.tsx
Accurate documenation of how to consume the Svelte package.
=> Update Svelte Package Documentation to display how to use the 'BrowserWalletState' proxy object.

apps/playground/src/pages/guides/nextjs.mdx, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-react/src/cardano-wallet/connected-button.tsx, packages/mesh-react/src/cardano-wallet/screen-p2p.tsx, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
this is to test if the new build works
=> change build for react package and bump version

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Cost models on mainnet has been updated.
=> Fix mainnet cost models

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
It is important that the inputs and mints are sorted, otherwise evaluated execution units won't match the input indexes.
Evaluation indexes are based on canonical ordering of the fields in the transaction, which unfortunately means that we have to sort them before going into serialization and evaluation.
=> fix unsorted inputs and mints

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/test/mesh-tx-builder/tx.test.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Two fixes happened in sidan-csl-rs, bumping the version should fix these. Outputs that contained no value info would incorrectly remove any inlined script/datum info. Also, it was not possible to output any value to Byron addresses.
Both these issues have been fixed.
=> Fix Byron Address Outputs

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/test/mesh-tx-builder/tx.test.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Byron address outputs were supported, but adding a Byron address to change address still caused issues, this has been fixed.
=> fix byron change output

apps/playground/src/components/cardano/connect-browser-wallet/index.tsx, apps/playground/src/pages/api/donate-mint-mesh.ts, apps/playground/src/pages/apis/txbuilder/basics/multisig.tsx, apps/playground/src/pages/apis/wallets/appwallet/sign-data.tsx, apps/playground/src/pages/apis/wallets/meshwallet/sign-data.tsx, apps/playground/src/pages/apis/wallets/meshwallet/sign-tx.tsx, apps/playground/src/pages/guides/multisig-tx/demo.tsx, package-lock.json, packages/mesh-common/package.json, packages/mesh-common/src/interfaces/signer.ts, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-provider/src/utxo-rpc.ts, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, packages/mesh-wallet/src/app/index.ts, packages/mesh-wallet/src/browser/webauthn/auth/connect.ts, packages/mesh-wallet/src/browser/webauthn/auth/login.ts, packages/mesh-wallet/src/browser/webauthn/auth/register.ts, packages/mesh-wallet/src/embedded/index.ts, packages/mesh-wallet/src/mesh/index.ts, packages/mesh-wallet/test/message-signing.test.ts, scripts/mesh-cli/package.json
had to standardize signtx and signdata. removing "sometimespromise".
=> Fix standardize signtx

package-lock.json, packages/mesh-provider/src/ogmios.ts
Ogmios Provider does not work currently. It uses incorrect method names and the wrong version of jsonrpc. 
> Please ensure that your pull …
=> Fix ogmios method name

packages/mesh-core-csl/src/offline-providers/offline-evaluator.ts
=> fix: fix bugs in offline eval

packages/mesh-common/src/data/json/credentials.ts, packages/mesh-common/src/data/mesh/credentials.ts
=> feat: add credential data utils

package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-common/src/utils/data-hash.ts, packages/mesh-common/test/drep/hash-drep-anchor.test.ts, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Using blake2bHex function was causing issues with packaging, change to using blake2b function instead
=> use blake2b instead of blake2bHex

packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-transaction/src/transaction/index.ts, packages/mesh-transaction/test/mesh-tx-builder/unbalanced-tx.test.ts
Add test case for unbalanced tx building
=> add test case for unbalance tx building

package-lock.json, packages/hydra/package.json, packages/hydra/src/hydra-provider.ts, packages/mesh-common/package.json, packages/mesh-common/src/interfaces/fetcher.ts, packages/mesh-common/src/types/transaction-info.ts, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-provider/src/blockfrost.ts, packages/mesh-provider/src/koios.ts, packages/mesh-provider/src/maestro.ts, packages/mesh-provider/src/offline/offline-fetcher.ts, packages/mesh-provider/src/utxo-rpc.ts, packages/mesh-provider/src/yaci.ts, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Add `fetchAddressTxs` implementation. The `TransactionInfo` type in common is updated with inputs and outputs info. Need upgrade all fetcher for full features.
TODO:
=> feat: add fetchAddressTxs

packages/mesh-core/src/utils/serializer.ts
Adding the utility function for serializing plutus data into cborhex format.
TODO:
=> feat: add serializer utils

package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core-cst/src/utils/data.ts, packages/mesh-core-cst/test/utils/serializer-utils.test.ts, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Bug fix for parse datum cbor, since 0 is falsy, the code incorrectly returns an error for ints of 0.
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> fix datum cbor parsing

packages/mesh-contract/src/escrow/aiken-workspace-v2/aiken.lock, packages/mesh-contract/src/escrow/aiken-workspace-v2/validators/escrow.ak, packages/mesh-contract/src/escrow/unbound-value/README.md, packages/mesh-contract/src/giftcard/infinite-mint/README.md, packages/mesh-contract/src/marketplace/insufficient-stake-control/README.md, packages/mesh-contract/src/plutus-nft/locked-value/README.md, packages/mesh-contract/src/swap/double-satisfaction/README.md, packages/mesh-contract/src/swap/double-satisfaction/aiken.lock, packages/mesh-contract/src/swap/double-satisfaction/validators/swap.ak
Add warning to bad contracts according to MR comments
=> feat: update bad contracts readme

packages/hydra/src/hydra-provider.ts
Change buildCommits from post to get and return the response
=> Change request from post to get / remove headers

package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/src/transaction/index.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
For some client node version it fails to resolve and install the hlabs's pair package. Adding it in package.json to force resolution.
=> chore: release

apps/playground/src/pages/guides/nextjs.mdx, package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-react/src/cardano-wallet/web3-services.tsx, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
improve `enable()` function to use auth provider
=> improve web3 wallet in react package

package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core-cst/src/message-signing/check-signature.ts, packages/mesh-core-cst/src/message-signing/generate-nonce.ts, packages/mesh-core-cst/src/message-signing/sign-data.ts, packages/mesh-core/package.json, packages/mesh-core/src/core.ts, packages/mesh-core/src/utils/resolver.ts, packages/mesh-core/src/utils/serializer.ts, packages/mesh-provider/package.json, packages/mesh-provider/src/blockfrost.ts, packages/mesh-provider/src/koios.ts, packages/mesh-provider/src/maestro.ts, packages/mesh-provider/src/ogmios.ts, packages/mesh-provider/src/utxo-rpc.ts, packages/mesh-provider/src/yaci.ts, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
- Bump dependency version for `core-csl` for offline tx eval bug
- Updated inline documentation for functions directly expecting devs to use at `core` and `provider`
=> feat: add inline docs for core and provider

packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, packages/mesh-wallet/src/mesh/index.ts, scripts/mesh-cli/package.json
https://github.com/MeshJS/mesh/issues/609
=> add init to get utxo and bump 1.9.0-beta-39

package-lock.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-common/src/data/json/aliases.ts, packages/mesh-common/src/data/json/index.ts, packages/mesh-common/src/data/mesh/aliases.ts, packages/mesh-common/test/data/json/aliases.test.ts, packages/mesh-common/test/data/mesh/aliases.test.ts, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Previously `mTuple` and `tuple` are fixed with 2 data. This release relaxes it to accept multiple arguments.
=> release: tuple of multiple data

packages/mesh-provider/package.json, packages/mesh-provider/src/utxo-rpc.ts
Implements `evaluateTx` and `fetchUTxOs` for u5c-provider and fixes `fetchAddressUTxOs`
> Please ensure that your pull request meets the …
=> feat: evaluateTx

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
=> Fix inputs sort

packages/mesh-wallet/src/browser/browser-wallet.ts
This issue was discussed at this discord dicussion: https://discord.com/channels/907191435864977459/1372480737487355974/1372480737487355974
It was recommended by Rice to remove these lines.
=> Remove fromUTF8() conversion in BrowserWallet.signData()

apps/playground/src/pages/aiken/first-script/script.tsx
=> Added `new` keyword to project creation command. (Typo fix)

apps/playground/src/data/links-solutions.ts
just adding cquistor on meshjs.dev
=> add cquistor link

apps/playground/src/pages/apis/txbuilder/basics/index.tsx, apps/playground/src/pages/apis/txbuilder/basics/script-metadata.tsx
> If you have any additional information or context to provide, such …
=> add playground entry for metadata script.

packages/bitcoin/package.json, packages/bitcoin/src/wallets/embedded/index.ts, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-hydra/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
- [x ] New feature (non-breaking change which adds functionality)
> If …
=> bitcoin sign tx

packages/mesh-provider/src/koios.ts
This PR fixes the Koios UTxO fetcher and introduces a full IEvaluator implementation for the Koios provider:
•	Bug fix – the UTxO fetcher now no longer drops script‐related fields.
•	New feature – adds evaluateTx(tx, additionalUtxos?, additionalTxs?) to KoiosProvider, exposing Koios → Ogmios transaction evaluation.
=> fix koios utxo fetcher, add koios tx evaluator

packages/bitcoin/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-csl/src/core/serializer.ts, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-hydra/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
=> Bump whisky

packages/mesh-provider/package.json, packages/mesh-provider/src/utxo-rpc.ts
> If you have any additional information or context to provide, such …
=> update fetchUTxOs + implement script part for utxo

apps/playground/src/pages/apis/utilities/blueprints/cli-blueprint.tsx, apps/playground/src/pages/apis/utilities/blueprints/index.tsx, package-lock.json, packages/bitcoin/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-hydra/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json, scripts/mesh-cli/src/actions/blueprint.ts, scripts/mesh-cli/src/actions/index.ts, scripts/mesh-cli/src/helpers/index.ts, scripts/mesh-cli/src/helpers/typeMap.ts, scripts/mesh-cli/src/index.ts
Implement npx meshjs blueprint <path-to-blueprint> <path to destination TS file>
https://github.com/MeshJS/mesh/issues/665
=> Feature blueprint parser

packages/bitcoin/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-hydra/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
> If you have any additional information or context to provide, such …
=> 1.9.0-beta.70

CONTRIBUTING.md, docs/component-owner.md
This pull request updates the project's contribution guidelines and adds a new guide for component owners. The main focus is to clarify workflows for triaging issues, managing project boards, and defining responsibilities for component owners. These changes aim to improve project organization and make it easier for contributors and maintainers to collaborate effectively.
**Enhancements to Contribution Guidelines:**
* Added a new "Core Workflow" section to `CONTRIBUTING.md`, outlining the process for triaging community issues, moving them into GitHub, and managing them through the project backlog and component owners.
* Removed detailed instructions about the pull request review and consensus process from `CONTRIBUTING.md` to streamline the document.
**New Documentation for Component …
=> docs: improve contributing
