MeshJS/mesh

packages/demo/pages/guides/smart-contract.tsx
Made 2 small fixes to the Smart Contract guide page:
1) Fixed incorrect datum variable name
2) Fixed link to the  "Designing Datum" section
=> Fixes for Smart Contract Guide

packages/module/src/core/CIP2.ts
This is a fix for this issue: https://github.com/MeshJS/mesh/issues/85
The `enoughValueHasBeenSelected` is currently reducing all amount quantities in each UTXO, when it should only be reducing amount quantities where it's unit matches the current passed in `asset.unit` value.
=> Fix for the `enoughValueHasBeenSelected` function

packages/react/package.json
Was getting a typescript error when using pnpm as the package manager. 
```
There are types at '.../node_modules/@meshsdk/react/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@meshsdk/react' library may need to update its package.json or typings.
```
The types field in package.json is no longer used if there is an exports field: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
https://stackoverflow.com/questions/76211877/the-xxxx-library-may-need-to-update-its-package-json-or-typings-ts
=> Fix type issue

packages/module/package.json
Fixes an issue where typescript types aren't pulled from "typings" if "exports" is also defined.
=> Fix type issue at build

packages/module/src/transaction/transaction.service.ts
Hi!,
This is a quite simple addition. I added the method `setTxRefInputs` in order to add reference inputs to the transaction. I tried to implement the tests but I didn't find where to do it. We can use this PR to communicate me further actions.
=> feat: add setTxRefInputs method

packages/module/package.json, packages/module/src/core/CIP8.ts, packages/module/src/core/CSL.ts, packages/module/src/transaction/transaction.service.ts, yarn.lock
Fixes the problem described in https://github.com/MeshJS/mesh/issues/124
by applying the solution described by https://github.com/Emurgo/cardano-serialization-lib/issues/157#issuecomment-1396933301.
---
This means switching the dependency of the cardano libs to `asmjs`.
---
I tested it with my Next.js 13 project using the new `app`-directory-structure and it works!
=> Fix compile issues with Next.js 13 using the app directory

packages/demo/pages/providers/maestro.tsx, packages/module/src/providers/maestro.provider.ts
Closes #172. See associated issue for more details.
=> Feat #172: `'amounts-as-strings': 'true'` for Maestro provider endpoints

packages/module/src/wallet/browser.service.ts
Add JSON.stringify to enable try/catch error handling
- errors are currently coming back with [Object object] in the message string
=> Add JSON.stringify to enable error on  browser.service.ts

packages/module/src/transaction/transaction.service.ts
I opened this issue: https://github.com/Emurgo/cardano-serialization-lib/issues/650 but I immediately closed it. Because I realised that the CSL has a special way to create a Plutus Witness without datum:
```rust
impl PlutusWitness {
...
pub fn new_with_ref(
script: &PlutusScriptSource,
datum: &DatumSource,
redeemer: &Redeemer,
) -> Self {
Self {
script: script.0.clone(),
datum: Some(datum.0.clone()),
redeemer: redeemer.clone(),
}
}
pub fn new_without_datum(script: &PlutusScript, redeemer: &Redeemer) -> Self {
Self {
script: PlutusScriptSourceEnum::Script(script.clone()),
datum: None,
redeemer: redeemer.clone(),
}
}
pub fn new_with_ref_without_datum(script: &PlutusScriptSource, redeemer: &Redeemer) -> Self {
Self {
script: script.0.clone(),
datum: None,
redeemer: redeemer.clone(),
}
}
... …
```
=> fix: redeem value with an inline datum

packages/core/src/wallet/embedded.service.ts
Wallet signing has this weird behaviour where if it cannot find a particular tx body utxo in a wallet's available utxos, it will append a weird payment key. I've removed this logic, and just skip over any tx body utxos it cannot find in wallet.
=> fix resolve input signer implementation

.github/ISSUE_TEMPLATE/-bug.md, .github/ISSUE_TEMPLATE/-docs.md, .github/ISSUE_TEMPLATE/-feature.md, .github/pull_request.template.md, packages/mesh-provider/src/offline/offline-fetcher.ts, packages/mesh-provider/test/offline/fetcher.test.ts
This pull request introduces an OfflineFetcher implementation for the Mesh SDK. The OfflineFetcher allows for offline storage and retrieval of Cardano blockchain data, including account information, UTxOs, asset metadata, block information, protocol parameters, and transactions. This addition will enable developers to work with Cardano data in offline environments or scenarios where direct access to third-party API's is not available or desired.
The main components of this PR include:
1. Implementation of the `OfflineFetcher` class, which implements the `IFetcher` interface.
2. Methods for adding various types of Cardano data to the offline data provider.
3. Fetch methods that retrieve stored data, mimicking online fetcher behavior.
4. Comprehensive input validation for all data types to …
=> Offile data provider

packages/mesh-react/src/stake-button/index.tsx
1. Re-enables the original delegateStake function
2. Brings it in sync with the registerAddress function (e.g. `onDelgated` logic)
3. Restores conditional behavior to delegateStake for already active accounts, and registerAddress for non active accounts.
Closes #355 
* I've marked everything as pass, deeming "not necessary" where applicable, as this mostly re-enables existing logic and is documented and fixes a bug introduced when the code/logic was removed.
* Existing tests are not passing, but that comes from the main branch. I do not observe any new test failures introduced from this branch.
N/A
=> [StakeButton] delegateStake when account active, otherwise registerStake

packages/mesh-core-cst/src/index.ts, packages/mesh-core-cst/src/plutus-tools/index.ts, packages/mesh-provider/src/blockfrost.ts, packages/mesh-provider/src/koios.ts, packages/mesh-provider/src/maestro.ts, packages/mesh-provider/src/yaci.ts
This PR normalizes Plutus script references across different providers by standardizing their encoding using the new `normalizePlutusScript` function. The change ensures consistent script representation and prevents potential issues with script hash comparison.
None specified
The key changes include:
1. Exporting plutus-tools utilities from core-cst package to make them available for providers
2. Modifying `normalizePlutusScript` to work with hex strings and enforce DoubleCBOR encoding for consistency
3. Updating script reference resolution in all providers (Blockfrost, Koios, Maestro, Yaci) to use normalized scripts
4. Adding infinite loop protection in plutus script bytes extraction
5. Adding error handling for missing script bytes in Maestro provider
=> Update ref script getters in  providers 

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Collateral inputs were included in incomplete tx ins, affecting the need for a fetcher in offline transactions. Since any reference scripts in collateral inputs do not affect fee calculations, it is possible to directly set the scriptSize of collateral inputs to 0, bypassing the inclusion of these scripts for fee calculations.
=> set scriptSize of collateral inputs to 0 to bypass fetcher logic

apps/playground/src/data/links-providers.ts, apps/playground/src/pages/providers/fetchers/index.tsx, apps/playground/src/pages/providers/offline-fetcher.tsx, packages/mesh-core-cst/src/index.ts, packages/mesh-provider/src/offline/offline-fetcher.ts, packages/mesh-provider/test/offline/fetcher.test.ts
This PR enhances the OfflineFetcher component with improved functionality and comprehensive documentation. The changes include:
- Enhanced `fetchAssetAddresses` to compile addresses from both registry and UTXOs for more complete results
- Added new `fetchAddressAssets` method to query assets held by an address
- Made epoch parameter optional in `fetchProtocolParameters` with fallback to max epoch
- Added detailed JSDoc documentation to all OfflineFetcher methods
- Created a new playground page with examples and usage instructions
- Added OfflineFetcher to the providers list and navigation
No related issues.
Key functionality improvements:
1. `fetchAssetAddresses` now provides more complete results by combining data from both the asset addresses registry and UTXOs
2. New …
=> OfflineFetcher Update

packages/mesh-core-cst/src/message-signing/check-signature.ts
I think I introduced an issue in a previous PR by using importing a CommonJS module incorrectly. I think instead it would be correct to import the Bip32PublicKey object with the proxy wrapper found in the wrapper.ts file.
> Please add the related issue here if any, e.g.:
>
> - https://github.com/MeshJS/mesh/issues/392
=> Use wrapper import for Bip32PublicKey object.

packages/mesh-wallet/src/mesh/index.ts
- set index numbers earlier in constructor
- send index numbers in signData
`MeshWallet` is targeted to have the ability to access an account at any index generated from an HD mnemonic (or a root private key). But it was not able to access any account other than the first one.
1. After rearranging some lines of code, `MeshWallet` is now able to utilize the provided `accountIndex` and `keyIndex` when an instance is created, which was not the case before, because `getAddressesFromWallet()` was getting called before setting those indexes.
2. In `MeshWallet`'s `signData()`, the `accountIndex` and `keyIndex` are now being passed to the EmbeddedWallet's signData().
Not any
=> Account index and key index fix in MeshWallet

packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, packages/mesh-wallet/src/mesh/index.ts, scripts/mesh-cli/package.json
- set index numbers earlier in constructor
- send index numbers in signData
`MeshWallet` is targeted to have the ability to access an account at any index generated from an HD mnemonic (or a root private key). But it was not able to access any account other than the first one.
1. After rearranging some lines of code, `MeshWallet` is now able to utilize the provided `accountIndex` and `keyIndex` when an instance is created, which was not the case before, because `getAddressesFromWallet()` was getting called before setting those indexes.
2. In `MeshWallet`'s `signData()`, the `accountIndex` and `keyIndex` are now being passed to the EmbeddedWallet's signData().
Not any
=> Account index fix

package-lock.json, packages/mesh-core-csl/package.json, packages/mesh-core-csl/src/utils/drep.ts, packages/mesh-core-csl/src/utils/index.ts, packages/mesh-core-csl/test/utils/drep.test.ts
Since CIP-129 has officially been merged, Mesh needs to add support for it. However, since CSL still only accepts CIP-105 DRepIds, our TxBuilder will currently only take CIP-105 DRepIds. But it should be simple to parse either CIP DReps with this utility.
While I have added a utility function that parses back and forth between CIP-105 and CIP-129 DRepIds, CSL currently still only accepts CIP-105 DRepIds, so currently, our TxBuilder is still only going to accept CIP-105 DRepIds. However, with the utility function, it would be possible to simply parse CIP-129 DRepIds and input the CIP-105 version into our TxBuilder.
=> Feature update/drep ids

apps/playground/src/components/sections/hero-logo-two-sections-links.tsx, apps/playground/src/data/links-aiken.ts, apps/playground/src/pages/aiken/index.tsx, apps/playground/src/pages/providers/blockfrost.tsx, apps/playground/src/pages/providers/koios.tsx, apps/playground/src/pages/providers/maestro.tsx, apps/playground/src/pages/providers/yaci.tsx, apps/playground/src/pages/yaci/index.tsx, apps/playground/src/types/menu-item.ts, package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/test/mesh-tx-builder/tx.test.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
recently cost models updated on the mainnet, but UPLC's VM didn't take the new builtins into account. They have updated this, so I have bumped UPLC version.
- [] Code refactoring (improving code quality without changing its behavior)
=> fix uplc for chang 2 cost models

package-lock.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-csl/src/offline-providers/offline-evaluator.ts, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Overlaps in collateral inputs and inputs in txHex causes issues when OfflineEvaluator checks for inputs to resolve
=> fix offline evaluator to compare resolved utxos vs inputs to resolve

package-lock.json, packages/mesh-common/src/interfaces/evaluator.ts, packages/mesh-common/src/types/transaction-builder/index.ts, packages/mesh-common/src/types/transaction-builder/txin.ts, packages/mesh-core-csl/package.json, packages/mesh-core-csl/src/offline-providers/offline-evaluator.ts, packages/mesh-core-csl/src/utils/transaction.ts, packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-transaction/src/mesh-tx-builder/tx-builder-core.ts
Add all-rounded support for offline eval, particularly user facing endpoints to supply additional txs and utxos.
- Frontend documentation is not included in this PR. Issue would be created on docs upon merge.
- Currently the tx-chaining only works for `OfflineEvaluator`. Needa update provider implementation one by one on the `evaluateTx` to make it work for other provider services.
=> feat: add tx chaining support in tx builder

package-lock.json, package.json, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-csl/test/offline-providers/evaluator.test.ts, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-transaction/src/mesh-tx-builder/index.ts, packages/mesh-transaction/src/mesh-tx-builder/tx-builder-core.ts, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
Fixing offline evaluator fail to provide extra utxo to wasm due to panic on empty string for plutus data. It changes to retaining as null rather than empty string to pass the rust type casting.
=> fix: fixing offline eval fail parsing input to rust

packages/hydra/src/hydra-instance.ts, packages/hydra/src/hydra-provider.ts
Axios sets "Content-Type": "application/json", which triggers a CORS preflight in buildCommit. 
=> fix content-type for hydra commits / add headers

packages/hydra/src/hydra-provider.ts
Fix websocket message for decommit tx
=> Fix websocket message for decommit tx

packages/mesh-transaction/src/mesh-tx-builder/index.ts
The error message from Blockfrost provider is of type string, which does not have a `.message` field. I have changed the error handling of MeshTxBuilder to handle different types of errors from the evaluator. But it may be better to either ensure all errors returned by everything is of type `Error`. Or extract an error handling layer.
=> parse errors for mesh tx builder eval

apps/playground/src/pages/about/about-us/hero.tsx, apps/playground/src/pages/providers/offline-fetcher.tsx, packages/hydra/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-provider/package.json, packages/mesh-provider/src/offline/offline-fetcher.ts, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
This PR adds a new `addSerializedTransaction` function to the OfflineFetcher class in the Mesh SDK. This function allows users to add a serialized transaction (in CBOR hex format) to the fetcher, which generates pseudo blocks, removes spent UTxOs, and adds new UTxOs from the transaction. This enhancement makes the OfflineFetcher more versatile for testing and offline development workflows.
N/A
=> Add addSerializedTransaction function to OfflineFetcher

packages/mesh-common/src/data/parser.ts, packages/mesh-core-cst/src/message-signing/check-signature.ts, packages/mesh-core-cst/src/message-signing/sign-data.ts, packages/mesh-core-cst/test/message-signing.test.ts
The current version of MeshJs, signData and checkSignature implementation specifies to accept any data (string). It does not throw any errors, leading to a problem when signing the string "XYZ" to instead sign an empty string. This happens because the Buffer decoding, will just take any …
=> fix a bug relating non hex string

packages/mesh-hydra/src/hydra-provider.ts
This pull request enhances the fetchUTxOs() function to support optional filtering by txHash and outputIndex.
Previously, the method returned all UTxOs from the snapshot. With this update, developers can now retrieve a specific UTxO (or multiple matching ones) by providing a transaction hash and optionally an output index.
This improves flexibility and efficiency when querying UTxOs, especially for constructing transactions.
> Please indicate …
=> feat: support filtering UTxOs by txHash and outputIndex

.github/workflows/publish.yml, packages/bitcoin/package.json, packages/mesh-common/package.json, packages/mesh-contract/package.json, packages/mesh-core-csl/package.json, packages/mesh-core-cst/package.json, packages/mesh-core/package.json, packages/mesh-hydra/package.json, packages/mesh-provider/package.json, packages/mesh-react/package.json, packages/mesh-svelte/package.json, packages/mesh-transaction/package.json, packages/mesh-wallet/package.json, scripts/mesh-cli/package.json
This pull request simplifies and standardizes the version comparison and publishing logic in the GitHub Actions workflow for the monorepo. The workflow now checks only the `mesh-core` package version to determine if any publish jobs should run, instead of tracking version changes for each individual package. All package versions and internal dependencies have also been bumped to `1.9.0-beta.73`.
Key changes:
**GitHub Actions workflow simplification:**
* The `.github/workflows/publish.yml` workflow now checks only `mesh-core`'s version to determine whether to trigger publishing for all packages, replacing individual version checks for each package. This reduces complexity and maintenance overhead. [[1]](diffhunk://#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7L34-R34 …
=> chore: release
